version: '3'
networks:
  local:
    driver: bridge
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    networks: 
      - local
  app:
    build: ./
    container_name: app
    restart: always
    environment: 
      MONGO_HOST: mongo:27017
      PORT: 3000
    ports:
      - '3000:3000'
    networks:
      - local