version: '3'
networks:
  local:
    driver: bridge
services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    ports:
      - '27017:27017'
    networks: 
      - local
  app:
    build: ./
    container_name: app
    restart: always
    environment: 
      MONGO_URI: mongodb://tiki:GFczZt27tXsmWtD@ds147965.mlab.com:47965/tiki
      PORT: 3001
    ports:
      - '3001:3001'
    networks:
      - local